version: '3.7'

networks:
  crowdfunding-network:
    name: crowdfunding-network
    
services:
  ###################################
  ##             MySQL             ##
  ###################################
  mysql:
    image: mysql
    volumes:
      - ${PWD}/data/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: 
      - mysql.env
    networks:
      - crowdfunding-network

  ###################################
  ##              Core             ##
  ###################################
  # Boot up the Particl Core (regnet)
  # TODO: move docker image into repo
  # TODO: move ports inside of docker image
  watcher-particl-core:
    image: ludx/particl
    volumes:
      - ${PWD}/data/particld:/root/.particl
    networks:
      - crowdfunding-network
   
  ###################################
  ##              PHP              ##
  ###################################
  # Boot up the crowdfunding network
  crowdfunding:
    image: crowdfunding-backend
    volumes:
      - ${PWD}/data/nginx:/var/www/html
      - ${PWD}/data/nginx/ccs-back/storage/app/proposals:/var/www/html/ccs-front/proposals
      - ${PWD}/data/nginx/ccs-back/storage/app/proposals.json:/var/www/html/ccs-front/_data/proposals.json
      - ${PWD}/data/nginx/ccs-back/storage/app/complete.json:/var/www/html/ccs-front/_data/completed-proposals.json
      - ${PWD}/ccs.env:/var/www/html/ccs-back/.env
      - ${PWD}/ccs.nginx:/etc/nginx/sites-enabled/ccs
      - ${PWD}/cron.py:/var/www/html/ccs-back/cron.py
      - ${PWD}/ccs-https.key:/etc/ssl/private/ccs-https.key
      - ${PWD}/ccs-https.crt:/etc/ssl/certs/ccs-https.crt
    ports:
      - "80:80"
      - "443:443"
    networks:
      - crowdfunding-network